### ISSUE TITLE
Remembering Pickaxe Tunnel Size Without Running Command

### ISSUE THREAD

**Issue by greenlinenshirt** [Tourmi/mc-server-side-vein-miner#45]
I want to use this mod with 1.21 for strip mining with 3x3 pickaxe. Which works great, but I have to keep running:

/svmm tunnel 3 3 50

This would be nice if it could lock this command in so it wouldn't need to be done every time.

Is this a current feature? or a way to force this?

Thank you.

**Comment by Tourmi** [comment]
I worry that without a way to undo tunneling, having a toggle could lead to costly mistakes, but I have still noted down the feature request in #26.

Otherwise, there's also these options that I find might help going faster
- You can type in just `/svmm tunnel` and the previous dimensions that were used with be remembered (until server restart)
- You can also just press the up arrow key in the chatbox to get the previous command
- Using a mod, or just a regular keyboard macro since most mods aren't updated to 1.21 yet, you may set a keybind that opens the chat, pastes the command, and presses enter, only a single keypress would be needed inbetween tunnels.
